#PAT generated
TOKEN = "API GENERADA DESDE PANEL DEL USUARIO"

# user name in Github
USUARIO = "NOMBRE DE USUARIO GITHUB"

API_URL = "https://api.github.com"

UBICACION_REPOSITORIO ="INDICAR LA RUTA DONDE QUEREMOS QUE SE VAYAN CREANDO POR DEFECTO LOS REPOSITORIOS"

PREFIJO = "repo_"